name: Terraform Setup
description: Checkout repository, authenticate to GCP, and install Terraform

inputs:
  terraform_wrapper:
    description: Enable the Terraform wrapper for output capture
    required: false
    default: 'false'
  gcp_wif_provider:
    description: GCP Workload Identity Federation provider
    required: true
  gcp_sa_email:
    description: GCP service account email
    required: true

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v7.0.0

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v3.0.0
      with:
        workload_identity_provider: ${{ inputs.gcp_wif_provider }}
        service_account: ${{ inputs.gcp_sa_email }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v4.0.1
      with:
        terraform_version: "1.15.6"
        terraform_wrapper: ${{ inputs.terraform_wrapper }}
