name: Terraform CD

on:
  push:
    branches:
      - main
    paths:
      - "**.tf"
      - "**.tfvars"
      - ".github/workflows/terraform-cd.yml"

permissions:
  contents: read
  id-token: write

jobs:
  terraform-apply:
    name: Apply to production
    runs-on: ubuntu-24.04
    environment: production
    defaults:
      run:
        shell: bash

    steps:
      - name: Setup
        uses: ./.github/actions/terraform-setup

      - name: Terraform init
        run: |
          terraform init \
            -backend-config="bucket=${{ vars.TF_STATE_BUCKET }}" \
            -input=false

      - name: Terraform plan
        run: |
          terraform plan \
            -var="project_id=${{ vars.GCP_PROJECT_ID }}" \
            -var="region=${{ vars.GCP_REGION }}" \
            -out=plan.tfplan \
            -input=false

      - name: Terraform apply
        run: |
          terraform apply \
            -auto-approve \
            -input=false \
            plan.tfplan
